
        <tr>
          <td class="eBody pdTp32" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 32px;padding-bottom: 0;padding-left: 16px;padding-right: 16px;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;width: 512px;color: #242424;background-color: #ffffff;"><p style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 24px;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;font-size: 14px;line-height: 22px;text-align: left;">Hey! COI Team,<br><br />
              Quotation <strong><?php echo $quote_key;?></strong> requested by "<?php echo $user_info->fullname;?>" has been reviewed by "<?php echo $admin_user->fullname;?>". Below are the summary of review.</p></td>
          <!-- end .eBody--> 
        </tr>
       
        <tr>
            <td colspan="5" class="width448 eTotal alignLeft" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 16px;padding-bottom: 14px;padding-left: 16px;padding-right: 16px;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;text-align: justify;vertical-align: middle;width: 448px;border-bottom: 1px solid #ebebeb; border-top: 1px solid #ebebeb; font-size: 14px;line-height: 19px;color: #242424;background-color: #fefefe;"><strong>Review Summary</strong></td>
        </tr>
          
        <tr>
          <td class="highlight invoiceHead" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 16px;padding-bottom: 0;padding-left: 16px;padding-right: 16px;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;width: 512px;text-align: left;font-size: 12px;color: #898989;background-color: #fafafa;border-bottom: 1px solid #ebebeb;"><table width="100%" border="0" cellspacing="0" cellpadding="0" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;mso-table-lspace: 0pt;mso-table-rspace: 0pt;border-collapse: collapse;border-spacing: 0;">
              
              <tr>
                <td align="left" valign="top" class="width132 pdRg16" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 16px;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;text-align: left;vertical-align: top;width: 132px;font-size: 12px;color: #898989;"><table border="0" cellpadding="0" cellspacing="0" class="tag" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;mso-table-lspace: 0pt;mso-table-rspace: 0pt;border-collapse: collapse;border-spacing: 0;">
                    <tr>
                      <td width="2" height="2" align="left" valign="top" class="btnLfTp" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;background-color: #0dc0c0;text-align: left;font-size: 0 !important;color: #898989;line-height: 100%;width: 2px;height: 2px;vertical-align: top;"><img src="https://portal.cutoutimage.com/assets/email/tag_lftp.png" width="2" height="2" style="margin-top: 0;margin-left: 0;margin-right: auto;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;height: 2px;width: 2px;line-height: 0 !important;outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;font-size: 0 !important;"></td>
                      <td width="4" class="emptyCell" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;text-align: left;font-size: 0 !important;color: #898989;background-color: #0dc0c0;line-height: 0 !important;">&nbsp;</td>
                      <td width="4" height="8" align="right" valign="top" class="btnRgTp" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;background-color: #0dc0c0;text-align: right;font-size: 0 !important;color: #898989;line-height: 100%;width: 2px;height: 2px;vertical-align: top;"><img src="https://portal.cutoutimage.com/assets/email/tag_rgtp.png" width="2" height="2" style="margin-top: 0;margin-left: auto;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;height: 2px;width: 2px;line-height: 0 !important;outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;font-size: 0 !important;"></td>
                    </tr>
                    <tr>
                      <td width="4" class="emptyCell" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;text-align: left;font-size: 0 !important;color: #898989;background-color: #0dc0c0;line-height: 0 !important;">&nbsp;</td>
                      <td align="left" valign="middle" class="tagName" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 2px;padding-bottom: 2px;padding-left: 4px;padding-right: 4px;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;text-align: left;font-size: 11px;color: #ffffff;background-color: #0dc0c0;text-transform: uppercase;white-space: nowrap;"><strong>Unit Price:</strong>&nbsp;</strong>&nbsp;US $<?php echo $flat_rate;?></td>
                      <td width="4" class="emptyCell" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;text-align: left;font-size: 0 !important;color: #898989;background-color: #0dc0c0;line-height: 0 !important;">&nbsp;</td>
                    </tr>
                    <tr>
                      <td align="left" valign="bottom" class="btnLfBt" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;background-color: #0dc0c0;text-align: left;font-size: 0 !important;color: #898989;line-height: 100%;width: 2px;height: 2px;vertical-align: bottom;"><img src="https://portal.cutoutimage.com/assets/email/tag_lfbt.png" width="2" height="2" style="margin-top: 0;margin-left: 0;margin-right: auto;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;height: 2px;width: 2px;line-height: 0 !important;outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;font-size: 0 !important;"></td>
                      <td width="4" class="emptyCell" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;text-align: left;font-size: 0 !important;color: #898989;background-color: #0dc0c0;line-height: 0 !important;">&nbsp;</td>
                      <td align="right" valign="bottom" class="btnRgBt" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;background-color: #0dc0c0;text-align: right;font-size: 0 !important;color: #898989;line-height: 100%;width: 2px;height: 2px;vertical-align: bottom;"><img src="https://portal.cutoutimage.com/assets/email/tag_rgbt.png" width="2" height="2" style="margin-top: 0;margin-left: auto;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;height: 2px;width: 2px;line-height: 0 !important;outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;font-size: 0 !important;"></td>
                    </tr>
                    <tr>
                      <td class="tag_space emptyCell" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;text-align: left;font-size: 0 !important;color: #898989;background-color: transparent;line-height: 0 !important;height: 4px;">&nbsp;</td>
                      <td class="tag_space emptyCell" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;text-align: left;font-size: 0 !important;color: #898989;background-color: transparent;line-height: 0 !important;height: 4px;">&nbsp;</td>
                      <td class="tag_space emptyCell" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;text-align: left;font-size: 0 !important;color: #898989;background-color: transparent;line-height: 0 !important;height: 4px;">&nbsp;</td>
                    </tr>
                  </table>
                  <p style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0px;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;font-size: 12px;line-height: 15px;text-align: left;color: #898989;"><span class="ihBlack" style="color: #242424;">&nbsp;</span></p></td>

                <td class="alignLeft" align="left" valign="top" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;text-align: left;font-size: 12px;color: #898989;"><table border="0" cellpadding="0" cellspacing="0" class="tag" style="margin-top: 0;margin-left: 0;margin-right: auto;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;mso-table-lspace: 0pt;mso-table-rspace: 0pt;border-collapse: collapse;border-spacing: 0;">
                    <tr>
                      <td width="2" height="2" align="left" valign="top" class="btnLfTp" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;background-color: #0dc0c0;text-align: left;font-size: 0 !important;color: #898989;line-height: 100%;width: 2px;height: 2px;vertical-align: top;"><img src="https://portal.cutoutimage.com/assets/email/tag_lftp.png" width="2" height="2" style="margin-top: 0;margin-left: 0;margin-right: auto;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;height: 2px;width: 2px;line-height: 0 !important;outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;font-size: 0 !important;"></td>
                      <td width="4" class="emptyCell" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;text-align: left;font-size: 0 !important;color: #898989;background-color: #0dc0c0;line-height: 0 !important;">&nbsp;</td>
                      <td width="4" height="8" align="right" valign="top" class="btnRgTp" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;background-color: #0dc0c0;text-align: right;font-size: 0 !important;color: #898989;line-height: 100%;width: 2px;height: 2px;vertical-align: top;"><img src="https://portal.cutoutimage.com/assets/email/tag_rgtp.png" width="2" height="2" style="margin-top: 0;margin-left: auto;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;height: 2px;width: 2px;line-height: 0 !important;outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;font-size: 0 !important;"></td>
                    </tr>
                    <tr>
                      <td width="4" class="emptyCell" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;text-align: left;font-size: 0 !important;color: #898989;background-color: #0dc0c0;line-height: 0 !important;">&nbsp;</td>
                      <td align="left" valign="middle" class="tagName" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 2px;padding-bottom: 2px;padding-left: 4px;padding-right: 4px;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;text-align: left;font-size: 11px;color: #ffffff;background-color: #0dc0c0;text-transform: uppercase;white-space: nowrap;"><strong>Quote Status:</strong>&nbsp;Reviewed</td>
                      <td width="4" class="emptyCell" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;text-align: left;font-size: 0 !important;color: #898989;background-color: #0dc0c0;line-height: 0 !important;">&nbsp;</td>
                    </tr>
                    <tr>
                      <td align="left" valign="bottom" class="btnLfBt" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;background-color: #0dc0c0;text-align: left;font-size: 0 !important;color: #898989;line-height: 100%;width: 2px;height: 2px;vertical-align: bottom;"><img src="https://portal.cutoutimage.com/assets/email/tag_lfbt.png" width="2" height="2" style="margin-top: 0;margin-left: 0;margin-right: auto;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;height: 2px;width: 2px;line-height: 0 !important;outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;font-size: 0 !important;"></td>
                      <td width="4" class="emptyCell" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;text-align: left;font-size: 0 !important;color: #898989;background-color: #0dc0c0;line-height: 0 !important;">&nbsp;</td>
                      <td align="right" valign="bottom" class="btnRgBt" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;background-color: #0dc0c0;text-align: right;font-size: 0 !important;color: #898989;line-height: 100%;width: 2px;height: 2px;vertical-align: bottom;"><img src="https://portal.cutoutimage.com/assets/email/tag_rgbt.png" width="2" height="2" style="margin-top: 0;margin-left: auto;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;height: 2px;width: 2px;line-height: 0 !important;outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;font-size: 0 !important;"></td>
                    </tr>
                    <tr>
                      <td class="tag_space emptyCell" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;text-align: left;font-size: 0 !important;color: #898989;background-color: transparent;line-height: 0 !important;height: 4px;">&nbsp;</td>
                      <td class="tag_space emptyCell" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;text-align: left;font-size: 0 !important;color: #898989;background-color: transparent;line-height: 0 !important;height: 4px;">&nbsp;</td>
                      <td class="tag_space emptyCell" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;text-align: left;font-size: 0 !important;color: #898989;background-color: transparent;line-height: 0 !important;height: 4px;">&nbsp;</td>
                    </tr>
                  </table>
                  <p class="ihBlack" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0px;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;font-size: 12px;line-height: 15px;text-align: left;color: #242424;">&nbsp;</p></td>
                  
              </tr>
            </table></td>
          <!-- end .highlight--> 
        </tr>
        <tr>
          <td class="eBody" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 16px;padding-bottom: 0;padding-left: 16px;padding-right: 16px;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;width: 512px;color: #242424;background-color: #ffffff;"><p style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 24px;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;font-size: 14px;line-height: 22px;text-align: justify;"><span style="font-style: oblique; color:#999999;">To know further information about user please login to COI Admin area.</span> <br /></p>
            <p style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 24px;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;font-size: 14px;line-height: 22px;text-align: left;">Thanking you,<br>
              <strong>COI System</strong></p></td>
          <!-- end .eBody--> 
        </tr>
      