        <tr>
          <td class="eBody pdBt16 alignLeft" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 16px;padding-bottom: 16px;padding-left: 16px;padding-right: 16px;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;text-align: left;width: 512px;color: #242424;background-color: #ffffff;"><p style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 24px;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;font-size: 14px;line-height: 22px;text-align: left;">Dear <?php echo $user_info->fullname;?>,</p>
            <p style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 24px;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;font-size: 14px;line-height: 22px;text-align: justify;">Thank you for requesting a quotation. We have reviewed your images of Quotation <strong><?php echo $quote_key;?></strong> and calculated prices as follows:</p>
              <table align="" cellspacing="0" cellpadding="0" border="0" style="margin-top: 10px;margin-left: auto;margin-right: auto;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;mso-table-lspace: 0pt;mso-table-rspace: 0pt;border-collapse: collapse;border-spacing: 0;width: 132px;text-align: left;" class="optionsButton">
                <tbody>
                  <tr>
                    <td align="left" valign="top" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;background-color: #0dc0c0;line-height: 100%;width: 4px;height: 5px;text-align: left;vertical-align: top;font-size: 0 !important;" class="btnLfTp"><img width="4" height="4" style="margin-top: 0;margin-left: 0;margin-right: auto;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;height: 4px;width: 4px;line-height: 0 !important;outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;font-size: 0 !important;" src="<?php echo $this->config->item('email_asset');?>/opBtn_lftp.png"></td>
                    <td style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;background-color: #0dc0c0;line-height: 0 !important;font-size: 0 !important;" class="emptyCell">&nbsp;</td>
                    <td style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;background-color: #0dc0c0;line-height: 0 !important;font-size: 0 !important;" class="emptyCell mobileHide">&nbsp;</td>
                    <td align="right" width="4" valign="top" height="8" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;background-color: #0dc0c0;line-height: 100%;width: 4px;height: 5px;text-align: right;vertical-align: top;font-size: 0 !important;" class="btnRgTp"><img width="4" height="4" style="margin-top: 0;margin-left: auto;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;height: 4px;width: 4px;line-height: 0 !important;outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;font-size: 0 !important;" src="<?php echo $this->config->item('email_asset');?>/opBtn_rgtp.png"></td>
                  </tr>
                  <tr>
                    <td style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;background-color: #0dc0c0;line-height: 0 !important;font-size: 0 !important;" class="emptyCell">&nbsp;</td>
                    <td style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;background-color: #0dc0c0;width: 20px;height: 16px;text-align: center;vertical-align: middle;" class="btnIcon"><span style="text-decoration: none;color: #ffffff;font-size: 35px; white-space: nowrap;">US $<?php echo $flat_rate;?> /</span></td>
                    <td style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 6px;padding-right: 2px;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;background-color: #0dc0c0;height: 16px;font-size: 18px;line-height: 16px;mso-line-height-rule: exactly;text-align: left;vertical-align: middle;" class="btnMain mobileHide"><a style="padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;display: inline-block;text-decoration: none;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;color: #ffffff;font-size: 12px;" href="https://portal.cutoutimage.com/auth/login"><span style="text-decoration: none;color: #ffffff;font-size: 12px;"> Per Image</span></a></td>
                    <td style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;background-color: #0dc0c0;line-height: 0 !important;font-size: 0 !important;" class="emptyCell">&nbsp;</td>
                  </tr>
                  <tr>
                    <td align="left" valign="bottom" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;background-color: #0dc0c0;line-height: 100%;width: 4px;height: 5px;text-align: left;vertical-align: bottom;font-size: 0 !important;" class="btnLfBt"><img width="4" height="4" style="margin-top: 0;margin-left: 0;margin-right: auto;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;height: 4px;width: 4px;line-height: 0 !important;outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;font-size: 0 !important;" src="<?php echo $this->config->item('email_asset');?>/opBtn_lfbt.png"></td>
                    <td style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;background-color: #0dc0c0;line-height: 0 !important;font-size: 0 !important;" class="emptyCell">&nbsp;</td>
                    <td style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;background-color: #0dc0c0;line-height: 0 !important;font-size: 0 !important;" class="emptyCell mobileHide">&nbsp;</td>
                    <td align="right" valign="bottom" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;background-color: #0dc0c0;line-height: 100%;width: 4px;height: 5px;text-align: right;vertical-align: bottom;font-size: 0 !important;" class="btnRgBt"><img width="4" height="4" style="margin-top: 0;margin-left: auto;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;height: 4px;width: 4px;line-height: 0 !important;outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;font-size: 0 !important;" src="<?php echo $this->config->item('email_asset');?>/opBtn_rgbt.png"></td>
                  </tr>
              </tbody>
            </table>
          </td>
        </tr>
        <tr>
          <td class="eBody pdBt16 alignLeft" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 16px;padding-bottom: 16px;padding-left: 16px;padding-right: 16px;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;text-align: left;width: 512px;color: #242424;background-color: #ffffff;">
            <p style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 24px;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;font-size: 14px;line-height: 22px;text-align: justify;">Please visit <a href="https://portal.cutoutimage.com/quotations" style="padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;display: inline-block;text-decoration: none;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;color: #0dc0c0;"><span style="text-decoration: none;color: #0dc0c0;font-weight: bold;">Quotation List</span></a> section of your account area to accept the quotation and proceed with uploading images. If you have any query please be kind to let us know. We will gladly assist you.</p> <br>
            Best Regards,<br> 
            <strong>Cut Out Image Team</strong></p>
          </td> <!-- end .eBody--> 
        </tr>