        <tr>
          <td class="highlight pdTp32" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 32px;padding-bottom: 0;padding-left: 16px;padding-right: 16px;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;width: 512px;text-align: center;background-color: #fafafa;border-bottom: 1px solid #ebebeb;"><h1 style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom:  25px;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;font-size: 24px;line-height: 36px;font-weight: bold;color: #242424;"><span style="color: #242424;">Welcome To Cut Out Image</span></h1>
            
          </td>
          <!-- end .highlight--> 
        </tr>
        <tr>
          <td class="eBody alignCenter pdTp32" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 32px;padding-bottom: 0;padding-left: 16px;padding-right: 16px;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;text-align: justify;width: 512px;color: #242424;background-color: #ffffff;"><p style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 24px;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;text-align: justify;font-size: 14px;line-height: 22px;">Dear <?php echo $invite_to_name;?><br /><br />You have been invited by "<strong><?php echo $invited_by_name;?></strong>" to join in "<strong style="color: #0dc0c0;"><?php echo $company_name;?></strong>" on www.cutoutimage.com as a admin/manager. Please click on the button below to accept the invitation.<br /><br />Best regards,<br /><strong>Cut Out Image Team</strong></p>
           
          </td>
        </tr>

        <tr>
          <td class="highlight pdTp32" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 32px;padding-bottom: 0;padding-left: 16px;padding-right: 16px;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;width: 512px;text-align: center;background-color: #fafafa;border-top: 1px solid #dddddd;">

          <table border="0" cellpadding="0" cellspacing="0" class="mainBtn" style="margin-top: 0;margin-left: auto;margin-right: auto;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;mso-table-lspace: 0pt;mso-table-rspace: 0pt;border-collapse: collapse;border-spacing: 0;">
              <tr>
                <td width="4" height="8" align="left" valign="top" class="btnLfTp" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;background-color: #0dc0c0;line-height: 100%;width: 4px;height: 4px;text-align: left;vertical-align: top;font-size: 0 !important;"><img src="<?php echo $this->config->item('email_asset');?>/mainBtn_lftp.png" width="4" height="4" style="margin-top: 0;margin-left: 0;margin-right: auto;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;height: 4px;width: 4px;line-height: 0 !important;outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;font-size: 0 !important;"></td>
                <td class="emptyCell" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;background-color: #0dc0c0;line-height: 0 !important;font-size: 0 !important;">&nbsp;</td>
                <td width="4" height="8" align="right" valign="top" class="btnRgTp" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;background-color: #0dc0c0;line-height: 100%;width: 4px;height: 4px;text-align: right;vertical-align: top;font-size: 0 !important;"><img src="<?php echo $this->config->item('email_asset');?>/mainBtn_rgtp.png" width="4" height="4" style="margin-top: 0;margin-left: auto;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;height: 4px;width: 4px;line-height: 0 !important;outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;font-size: 0 !important;"></td>
              </tr>
              <tr>
                <td class="emptyCell" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;background-color: #0dc0c0;line-height: 0 !important;font-size: 0 !important;">&nbsp;</td>
                <td class="btnMain" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 8px;padding-bottom: 8px;padding-left: 18px;padding-right: 18px;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;background-color: #0dc0c0;height: 20px;font-size: 18px;line-height: 20px;mso-line-height-rule: exactly;text-align: center;vertical-align: middle;"><a href="<?php echo $invite_url;?>" style="padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;display: inline-block;text-decoration: none;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;color: #ffffff;font-weight: bold;"><span style="text-decoration: none;color: #ffffff;">Accept Invitation</span></a></td>
                <td class="emptyCell" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;background-color: #0dc0c0;line-height: 0 !important;font-size: 0 !important;">&nbsp;</td>
              </tr>
              <tr>
                <td align="left" valign="bottom" class="btnLfBt" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;background-color: #0dc0c0;line-height: 100%;width: 4px;height: 4px;text-align: left;vertical-align: bottom;font-size: 0 !important;"><img src="<?php echo $this->config->item('email_asset');?>/mainBtn_lfbt.png" width="4" height="4" style="margin-top: 0;margin-left: 0;margin-right: auto;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;height: 4px;width: 4px;line-height: 0 !important;outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;font-size: 0 !important;"></td>
                <td class="emptyCell" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;background-color: #0dc0c0;line-height: 0 !important;font-size: 0 !important;">&nbsp;</td>
                <td align="right" valign="bottom" class="btnRgBt" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;background-color: #0dc0c0;line-height: 100%;width: 4px;height: 4px;text-align: right;vertical-align: bottom;font-size: 0 !important;"><img src="<?php echo $this->config->item('email_asset');?>/mainBtn_rgbt.png" width="4" height="4" style="margin-top: 0;margin-left: auto;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;height: 4px;width: 4px;line-height: 0 !important;outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;font-size: 0 !important;"></td>
              </tr>
            </table>
            <table align="center" border="0" cellpadding="0" cellspacing="0" class="subtleBtn" style="margin-top: 0;margin-left: auto;margin-right: auto;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;mso-table-lspace: 0pt;mso-table-rspace: 0pt;border-collapse: collapse;border-spacing: 0;">
              <tr>
                <td style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 16px;padding-bottom: 32px;padding-left: 0;padding-right: 0;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;font-size: 14px;color: #898989;"><a href="https://www.cutoutimage.com/contact-us" style="padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;display: inline-block;text-decoration: none;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;color: #898989;"><span style="text-decoration: none;color: #898989;">If you do not wish to accept the invitation please just ignore this email.</span></a></td>
              </tr>
            </table>  
            
          </td>
          <!-- end .highlight--> 
        </tr>
          <!-- end .eBody--> 
       