          <tr>
          <td class="eBody pdBt16 alignLeft" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 16px;padding-bottom: 16px;padding-left: 16px;padding-right: 16px;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;text-align: left;width: 512px;color: #242424;background-color: #ffffff;"><p style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 24px;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;font-size: 14px;line-height: 22px;text-align: left;">Dear <?php echo $user_info->fullname;?>,</p>
            <p style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 24px;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;font-size: 14px;line-height: 22px;text-align: justify;">Thank you! You have recently requested a quotation on behalf of <strong><?php echo $user_info->company;?></strong>. Below are the summary of your quotation made on <strong><?php echo date("F d, Y");?></strong>. <br /><br />We will review your request and get back to you shortly. You can also view your quotation status in the <a href="https://portal.cutoutimage.com/quotations" style="padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;display: inline-block;text-decoration: none;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;color: #0dc0c0;"><span style="text-decoration: none;color: #0dc0c0;font-weight: bold;">Quotation List</span></a> section of your account. <br /><br />Best Regards,<br /><strong>Cut Out Image Team</strong></p>
          </td>
          <!-- end .eBody--> 
        </tr>
        <tr>
            <td colspan="5" class="width448 eTotal alignLeft" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 16px;padding-bottom: 14px;padding-left: 16px;padding-right: 16px;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;text-align: left;vertical-align: middle;width: 448px;border-bottom: 1px solid #ebebeb; border-top: 1px solid #ebebeb; font-size: 14px;line-height: 19px;color: #242424;background-color: #fefefe;"><strong>Quotation&nbsp;Title:</strong>&nbsp;<?php echo (isset($job_title)) ? $job_title : '';?></td>
        </tr>

        <tr>
            <td colspan="5" class="width448 eTotal alignLeft" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 16px;padding-bottom: 14px;padding-left: 16px;padding-right: 16px;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;text-align: justify;vertical-align: middle;width: 448px;border-bottom: 1px solid #ebebeb; border-top: 1px solid #ebebeb; font-size: 14px;line-height: 19px;color: #242424;background-color: #fefefe;"><strong>Quotation&nbsp;Note:</strong>&nbsp;<?php echo (isset($job_desc)) ? $job_desc : '';?></td>
        </tr>
          
        <tr>
          <td class="highlight invoiceHead" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 16px;padding-bottom: 0;padding-left: 16px;padding-right: 16px;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;width: 512px;text-align: left;font-size: 12px;color: #898989;background-color: #fafafa;border-bottom: 1px solid #ebebeb;"><table width="100%" border="0" cellspacing="0" cellpadding="0" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;mso-table-lspace: 0pt;mso-table-rspace: 0pt;border-collapse: collapse;border-spacing: 0;">
              
              <tr>
                <td align="left" valign="top" class="width132 pdRg16" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 16px;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;text-align: left;vertical-align: top;width: 132px;font-size: 12px;color: #898989;"><table border="0" cellpadding="0" cellspacing="0" class="tag" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;mso-table-lspace: 0pt;mso-table-rspace: 0pt;border-collapse: collapse;border-spacing: 0;">
                    <tr>
                      <td width="2" height="2" align="left" valign="top" class="btnLfTp" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;background-color: #0dc0c0;text-align: left;font-size: 0 !important;color: #898989;line-height: 100%;width: 2px;height: 2px;vertical-align: top;"><img src="https://portal.cutoutimage.com/assets/email/tag_lftp.png" width="2" height="2" style="margin-top: 0;margin-left: 0;margin-right: auto;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;height: 2px;width: 2px;line-height: 0 !important;outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;font-size: 0 !important;"></td>
                      <td width="4" class="emptyCell" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;text-align: left;font-size: 0 !important;color: #898989;background-color: #0dc0c0;line-height: 0 !important;">&nbsp;</td>
                      <td width="4" height="8" align="right" valign="top" class="btnRgTp" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;background-color: #0dc0c0;text-align: right;font-size: 0 !important;color: #898989;line-height: 100%;width: 2px;height: 2px;vertical-align: top;"><img src="https://portal.cutoutimage.com/assets/email/tag_rgtp.png" width="2" height="2" style="margin-top: 0;margin-left: auto;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;height: 2px;width: 2px;line-height: 0 !important;outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;font-size: 0 !important;"></td>
                    </tr>
                    <tr>
                      <td width="4" class="emptyCell" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;text-align: left;font-size: 0 !important;color: #898989;background-color: #0dc0c0;line-height: 0 !important;">&nbsp;</td>
                      <td align="left" valign="middle" class="tagName" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 2px;padding-bottom: 2px;padding-left: 4px;padding-right: 4px;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;text-align: left;font-size: 11px;color: #ffffff;background-color: #0dc0c0;text-transform: uppercase;white-space: nowrap;"><strong>QUOTE ID:</strong>&nbsp;</strong>&nbsp;<?php echo (isset($quote_key)) ? 'COI-QR-'.$quote_key : '';?></td>
                      <td width="4" class="emptyCell" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;text-align: left;font-size: 0 !important;color: #898989;background-color: #0dc0c0;line-height: 0 !important;">&nbsp;</td>
                    </tr>
                    <tr>
                      <td align="left" valign="bottom" class="btnLfBt" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;background-color: #0dc0c0;text-align: left;font-size: 0 !important;color: #898989;line-height: 100%;width: 2px;height: 2px;vertical-align: bottom;"><img src="https://portal.cutoutimage.com/assets/email/tag_lfbt.png" width="2" height="2" style="margin-top: 0;margin-left: 0;margin-right: auto;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;height: 2px;width: 2px;line-height: 0 !important;outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;font-size: 0 !important;"></td>
                      <td width="4" class="emptyCell" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;text-align: left;font-size: 0 !important;color: #898989;background-color: #0dc0c0;line-height: 0 !important;">&nbsp;</td>
                      <td align="right" valign="bottom" class="btnRgBt" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;background-color: #0dc0c0;text-align: right;font-size: 0 !important;color: #898989;line-height: 100%;width: 2px;height: 2px;vertical-align: bottom;"><img src="https://portal.cutoutimage.com/assets/email/tag_rgbt.png" width="2" height="2" style="margin-top: 0;margin-left: auto;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;height: 2px;width: 2px;line-height: 0 !important;outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;font-size: 0 !important;"></td>
                    </tr>
                    <tr>
                      <td class="tag_space emptyCell" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;text-align: left;font-size: 0 !important;color: #898989;background-color: transparent;line-height: 0 !important;height: 4px;">&nbsp;</td>
                      <td class="tag_space emptyCell" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;text-align: left;font-size: 0 !important;color: #898989;background-color: transparent;line-height: 0 !important;height: 4px;">&nbsp;</td>
                      <td class="tag_space emptyCell" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;text-align: left;font-size: 0 !important;color: #898989;background-color: transparent;line-height: 0 !important;height: 4px;">&nbsp;</td>
                    </tr>
                  </table>
                  <p style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0px;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;font-size: 12px;line-height: 15px;text-align: left;color: #898989;"><span class="ihBlack" style="color: #242424;">&nbsp;</span></p></td>

                <td class="alignLeft" align="left" valign="top" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;text-align: left;font-size: 12px;color: #898989;"><table border="0" cellpadding="0" cellspacing="0" class="tag" style="margin-top: 0;margin-left: 0;margin-right: auto;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;mso-table-lspace: 0pt;mso-table-rspace: 0pt;border-collapse: collapse;border-spacing: 0;">
                    <tr>
                      <td width="2" height="2" align="left" valign="top" class="btnLfTp" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;background-color: #0dc0c0;text-align: left;font-size: 0 !important;color: #898989;line-height: 100%;width: 2px;height: 2px;vertical-align: top;"><img src="https://portal.cutoutimage.com/assets/email/tag_lftp.png" width="2" height="2" style="margin-top: 0;margin-left: 0;margin-right: auto;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;height: 2px;width: 2px;line-height: 0 !important;outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;font-size: 0 !important;"></td>
                      <td width="4" class="emptyCell" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;text-align: left;font-size: 0 !important;color: #898989;background-color: #0dc0c0;line-height: 0 !important;">&nbsp;</td>
                      <td width="4" height="8" align="right" valign="top" class="btnRgTp" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;background-color: #0dc0c0;text-align: right;font-size: 0 !important;color: #898989;line-height: 100%;width: 2px;height: 2px;vertical-align: top;"><img src="https://portal.cutoutimage.com/assets/email/tag_rgtp.png" width="2" height="2" style="margin-top: 0;margin-left: auto;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;height: 2px;width: 2px;line-height: 0 !important;outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;font-size: 0 !important;"></td>
                    </tr>
                    <tr>
                      <td width="4" class="emptyCell" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;text-align: left;font-size: 0 !important;color: #898989;background-color: #0dc0c0;line-height: 0 !important;">&nbsp;</td>
                      <td align="left" valign="middle" class="tagName" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 2px;padding-bottom: 2px;padding-left: 4px;padding-right: 4px;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;text-align: left;font-size: 11px;color: #ffffff;background-color: #0dc0c0;text-transform: uppercase;white-space: nowrap;"><strong>TAT:</strong>&nbsp;<?php echo ($quote_details->turnaround_time > 0) ? $quote_details->turnaround_time . ' Hours' : 'FX';?></td>
                      <td width="4" class="emptyCell" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;text-align: left;font-size: 0 !important;color: #898989;background-color: #0dc0c0;line-height: 0 !important;">&nbsp;</td>
                    </tr>
                    <tr>
                      <td align="left" valign="bottom" class="btnLfBt" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;background-color: #0dc0c0;text-align: left;font-size: 0 !important;color: #898989;line-height: 100%;width: 2px;height: 2px;vertical-align: bottom;"><img src="https://portal.cutoutimage.com/assets/email/tag_lfbt.png" width="2" height="2" style="margin-top: 0;margin-left: 0;margin-right: auto;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;height: 2px;width: 2px;line-height: 0 !important;outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;font-size: 0 !important;"></td>
                      <td width="4" class="emptyCell" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;text-align: left;font-size: 0 !important;color: #898989;background-color: #0dc0c0;line-height: 0 !important;">&nbsp;</td>
                      <td align="right" valign="bottom" class="btnRgBt" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;background-color: #0dc0c0;text-align: right;font-size: 0 !important;color: #898989;line-height: 100%;width: 2px;height: 2px;vertical-align: bottom;"><img src="https://portal.cutoutimage.com/assets/email/tag_rgbt.png" width="2" height="2" style="margin-top: 0;margin-left: auto;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;height: 2px;width: 2px;line-height: 0 !important;outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;font-size: 0 !important;"></td>
                    </tr>
                    <tr>
                      <td class="tag_space emptyCell" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;text-align: left;font-size: 0 !important;color: #898989;background-color: transparent;line-height: 0 !important;height: 4px;">&nbsp;</td>
                      <td class="tag_space emptyCell" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;text-align: left;font-size: 0 !important;color: #898989;background-color: transparent;line-height: 0 !important;height: 4px;">&nbsp;</td>
                      <td class="tag_space emptyCell" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;text-align: left;font-size: 0 !important;color: #898989;background-color: transparent;line-height: 0 !important;height: 4px;">&nbsp;</td>
                    </tr>
                  </table>
                  <p class="ihBlack" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0px;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;font-size: 12px;line-height: 15px;text-align: left;color: #242424;">&nbsp;</p></td>

                <td class="alignRight" align="right" valign="top" class="width184 pdRg16" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 16px;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;text-align: left;vertical-align: top;width: 184px;font-size: 12px;color: #898989;"><table border="0" cellpadding="0" cellspacing="0" class="tag" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;mso-table-lspace: 0pt;mso-table-rspace: 0pt;border-collapse: collapse;border-spacing: 0;">
                    <tr>
                      <td width="2" height="2" align="left" valign="top" class="btnLfTp" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;background-color: #0dc0c0;text-align: left;font-size: 0 !important;color: #898989;line-height: 100%;width: 2px;height: 2px;vertical-align: top;"><img src="https://portal.cutoutimage.com/assets/email/tag_lftp.png" width="2" height="2" style="margin-top: 0;margin-left: 0;margin-right: auto;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;height: 2px;width: 2px;line-height: 0 !important;outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;font-size: 0 !important;"></td>
                      <td width="4" class="emptyCell" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;text-align: left;font-size: 0 !important;color: #898989;background-color: #0dc0c0;line-height: 0 !important;">&nbsp;</td>
                      <td width="4" height="8" align="right" valign="top" class="btnRgTp" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;background-color: #0dc0c0;text-align: right;font-size: 0 !important;color: #898989;line-height: 100%;width: 2px;height: 2px;vertical-align: top;"><img src="https://portal.cutoutimage.com/assets/email/tag_rgtp.png" width="2" height="2" style="margin-top: 0;margin-left: auto;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;height: 2px;width: 2px;line-height: 0 !important;outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;font-size: 0 !important;"></td>
                    </tr>
                    <tr>
                      <td width="4" class="emptyCell" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;text-align: left;font-size: 0 !important;color: #898989;background-color: #0dc0c0;line-height: 0 !important;">&nbsp;</td>
                      <td align="left" valign="middle" class="tagName" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 2px;padding-bottom: 2px;padding-left: 4px;padding-right: 4px;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;text-align: left;font-size: 11px;color: #ffffff;background-color: #0dc0c0;text-transform: uppercase;white-space: nowrap;"><strong>RFF:</strong>&nbsp;<?php echo $quote_details->return_file_format;?></td>
                      <td width="4" class="emptyCell" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;text-align: left;font-size: 0 !important;color: #898989;background-color: #0dc0c0;line-height: 0 !important;">&nbsp;</td>
                    </tr>
                    <tr>
                      <td align="left" valign="bottom" class="btnLfBt" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;background-color: #0dc0c0;text-align: left;font-size: 0 !important;color: #898989;line-height: 100%;width: 2px;height: 2px;vertical-align: bottom;"><img src="https://portal.cutoutimage.com/assets/email/tag_lfbt.png" width="2" height="2" style="margin-top: 0;margin-left: 0;margin-right: auto;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;height: 2px;width: 2px;line-height: 0 !important;outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;font-size: 0 !important;"></td>
                      <td width="4" class="emptyCell" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;text-align: left;font-size: 0 !important;color: #898989;background-color: #0dc0c0;line-height: 0 !important;">&nbsp;</td>
                      <td align="right" valign="bottom" class="btnRgBt" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;background-color: #0dc0c0;text-align: right;font-size: 0 !important;color: #898989;line-height: 100%;width: 2px;height: 2px;vertical-align: bottom;"><img src="https://portal.cutoutimage.com/assets/email/tag_rgbt.png" width="2" height="2" style="margin-top: 0;margin-left: auto;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;height: 2px;width: 2px;line-height: 0 !important;outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;font-size: 0 !important;"></td>
                    </tr>
                    <tr>
                      <td class="tag_space emptyCell" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;text-align: left;font-size: 0 !important;color: #898989;background-color: transparent;line-height: 0 !important;height: 4px;">&nbsp;</td>
                      <td class="tag_space emptyCell" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;text-align: left;font-size: 0 !important;color: #898989;background-color: transparent;line-height: 0 !important;height: 4px;">&nbsp;</td>
                      <td class="tag_space emptyCell" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;text-align: left;font-size: 0 !important;color: #898989;background-color: transparent;line-height: 0 !important;height: 4px;">&nbsp;</td>
                    </tr>
                  </table>
                  <p class="amount" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0px;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;color: #242424;font-size: 12px;line-height: 15px;text-align: left;font-weight: bold;">&nbsp;</p></td>
                  
              </tr>
            </table></td>
          <!-- end .highlight--> 
        </tr>

        <tr>
          <td style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;"><table width="100%" border="0" cellpadding="0" cellspacing="0" class="invoiceTable2 invoiceTable3" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;mso-table-lspace: 0pt;mso-table-rspace: 0pt;border-collapse: collapse;border-spacing: 0;background-color: #ffffff;">
              <tr>
                <th colspan="2" class="alignLeft pdLf16" style="-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;text-align: left;padding-left: 16px;padding-top: 6px;padding-bottom: 6px;padding-right: 16px;font-size: 12px;line-height: 16px;font-weight: bold;text-transform: uppercase;border-bottom: 1px solid #ebebeb;color: #898989;background-color: #ffffff;">Service Check List</th>
                <th class="width80 alignCenter" style="-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;text-align: center;vertical-align: middle;width: 80px;padding-top: 6px;padding-bottom: 6px;padding-left: 0;padding-right: 16px;font-size: 12px;line-height: 16px;font-weight: bold;text-transform: uppercase;border-bottom: 1px solid #ebebeb;color: #898989;background-color: #ffffff;">Image Qty</th>
                <th colspan="2" class="alignCenter eQuantity" style="-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;text-align: center;padding-top: 6px;padding-bottom: 6px;padding-left: 0;padding-right: 0;font-size: 12px;line-height: 16px;font-weight: bold;text-transform: uppercase;border-bottom: 1px solid #ebebeb;color: #898989;background-color: #ffffff;width: 40px;vertical-align: middle; width: 80px;">Unit Price</th>
                <!-- <th class="width80 alignRight" style="-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;text-align: right;vertical-align: middle;width: 80px;padding-top: 6px;padding-bottom: 6px;padding-left: 0;padding-right: 16px;font-size: 12px;line-height: 16px;font-weight: bold;text-transform: uppercase;border-bottom: 1px solid #ebebeb;color: #898989;background-color: #ffffff;">Total</th> -->
              </tr>
              <tr>
                <td colspan="5" class="alignLeft prodTitle" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 12px;padding-bottom: 0;padding-left: 16px;padding-right: 16px;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;text-align: left;font-size: 14px;line-height: 19px;color: #242424;background-color: #ffffff;border-bottom: 0;border-top: 1px solid #ebebeb;"><h4 style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 5px;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;font-size: 14px;font-weight: bold;color: #242424;"><a href="#" style="padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;display: inline-block;text-decoration: none;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;color: #0dc0c0;">Cut Out / Clipping Path</a></h4></td>
              </tr>
              <tr>
               
                <td colspan="2" class="alignLeft prodDesc" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 14px;padding-left: 16px;padding-right: 8px;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;text-align: left;font-size: 12px;line-height: 18px;color: #898989;background-color: #ffffff;vertical-align: top;"><?php echo job_options($quote_details,$flag='email');?></td>
                <td class="width80 alignCenter" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 14px;padding-left: 0;padding-right: 16px;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;text-align: center;vertical-align: middle;width: 80px;font-size: 14px;line-height: 19px;color: #242424;background-color: #ffffff;"><span class="desktopHide" style="display: none;font-size: 0;max-height: 0;width: 0;line-height: 0;overflow: hidden;mso-hide: all;">Image Quantity: </span><?php echo $quote_details->quantity;?></td>
                <td colspan="2" class="alignCenter eQuantity" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 14px;padding-left: 0;padding-right: 0;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;text-align: center;font-size: 14px;line-height: 19px;color: #242424;background-color: #ffffff;width: 40px;vertical-align: middle;"><span class="desktopHide" style="display: none;font-size: 0;max-height: 0;width: 0;line-height: 0;overflow: hidden;mso-hide: all;">Unit Price: </span>Requested</td>
                <!-- <td class="width80 alignRight" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 14px;padding-left: 0;padding-right: 16px;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;text-align: right;vertical-align: middle;width: 80px;font-size: 14px;line-height: 19px;color: #242424;background-color: #ffffff;"><span class="desktopHide" style="display: none;font-size: 0;max-height: 0;width: 0;line-height: 0;overflow: hidden;mso-hide: all;">TOTAL: </span><span class="amount" style="color: #666666;">$170.00</span></td> -->
              </tr>
            
              <!-- <tr>
                <td colspan="4" class="width448 subTotal alignRight mobileHide" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 16px;padding-bottom: 14px;padding-left: 0;padding-right: 6px;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;text-align: right;vertical-align: middle;width: 448px;border-bottom: 1px solid #ebebeb;font-size: 14px;line-height: 22px;color: #666666;background-color: #fafafa; font-weight:bold;">Total</td>
                <td class="width80 subTotal alignRight" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 16px;padding-bottom: 14px;padding-left: 0;padding-right: 16px;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;text-align: right;vertical-align: middle;width: 80px;border-bottom: 1px solid #ebebeb;font-size: 14px;line-height: 22px;color: #898989;background-color: #fafafa;"><span class="desktopHide" style="display: none;font-size: 0;max-height: 0;width: 0;line-height: 0;overflow: hidden;mso-hide: all; font-weight:bold;color:#666666;">Total</span><span class="amount" style="color: #393939; font-weight:bold;">$170.00</span></td>
              </tr> -->
              <tr>
                <td colspan="5" class="width448 eTotal alignCenter" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 16px;padding-bottom: 14px;padding-left: 16px;padding-right: 16px;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;text-align: center;vertical-align: middle;width: 448px;border-bottom: 1px solid #ebebeb;border-top: 1px solid #ebebeb;font-size: 14px;line-height: 19px;color: #242424;background-color: #ffffff;">Total Due By - <?php echo date("F d, Y");?>: <strong style="color:#ff0000;">US $<?php echo $this->notifications->total_due;?></strong></td>
                
              </tr>
            </table></td>
          <!-- end order body --> 
        </tr>