        <tr>
          <td class="eBody pdBt16 alignLeft" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 16px;padding-bottom: 16px;padding-left: 16px;padding-right: 16px;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;text-align: left;width: 512px;color: #242424;background-color: #ffffff;"><p style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 24px;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;font-size: 14px;line-height: 22px;text-align: left;">Hello John Klem,</p>
            <p style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 24px;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;font-size: 14px;line-height: 22px;text-align: left;">Here is a summary of your recent order made on <strong>Mar 15, 2014</strong>. You can also view your order in the <a href="#" style="padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;display: inline-block;text-decoration: none;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;color: #0dc0c0;"><span style="text-decoration: none;color: #0dc0c0;font-weight: bold;">Purchases</span></a> section of your account. </p>
            <table border="0" cellpadding="0" cellspacing="0" class="defaultBtn" style="margin-top: 0;margin-left: 0;margin-right: auto;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;mso-table-lspace: 0pt;mso-table-rspace: 0pt;border-collapse: collapse;border-spacing: 0;">
              <tr>
                <td width="4" height="8" align="left" valign="top" class="btnLfTp" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;background-color: #424242;line-height: 100%;width: 4px;height: 4px;text-align: left;vertical-align: top;font-size: 0 !important;"><img src="<?php echo $this->config->item('email_asset');?>/mainBtn_lftp.png" width="4" height="4" style="margin-top: 0;margin-left: 0;margin-right: auto;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;height: 4px;width: 4px;line-height: 0 !important;outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;font-size: 0 !important;"></td>
                <td class="emptyCell" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;background-color: #424242;line-height: 0 !important;font-size: 0 !important;">&nbsp;</td>
                <td width="4" height="8" align="right" valign="top" class="btnRgTp" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;background-color: #424242;line-height: 100%;width: 4px;height: 4px;text-align: right;vertical-align: top;font-size: 0 !important;"><img src="<?php echo $this->config->item('email_asset');?>/mainBtn_rgtp.png" width="4" height="4" style="margin-top: 0;margin-left: auto;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;height: 4px;width: 4px;line-height: 0 !important;outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;font-size: 0 !important;"></td>
              </tr>
              <tr>
                <td class="emptyCell" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;background-color: #424242;line-height: 0 !important;font-size: 0 !important;">&nbsp;</td>
                <td class="btnMain" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 8px;padding-bottom: 8px;padding-left: 18px;padding-right: 18px;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;background-color: #424242;height: 20px;font-size: 18px;line-height: 20px;mso-line-height-rule: exactly;text-align: center;vertical-align: middle;"><a href="#" style="padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;display: inline-block;text-decoration: none;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;color: #ffffff;"><span style="text-decoration: none;color: #ffffff;">Order Details</span></a></td>
                <td class="emptyCell" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;background-color: #424242;line-height: 0 !important;font-size: 0 !important;">&nbsp;</td>
              </tr>
              <tr>
                <td align="left" valign="bottom" class="btnLfBt" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;background-color: #424242;line-height: 100%;width: 4px;height: 4px;text-align: left;vertical-align: bottom;font-size: 0 !important;"><img src="<?php echo $this->config->item('email_asset');?>/mainBtn_lfbt.png" width="4" height="4" style="margin-top: 0;margin-left: 0;margin-right: auto;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;height: 4px;width: 4px;line-height: 0 !important;outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;font-size: 0 !important;"></td>
                <td class="emptyCell" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;background-color: #424242;line-height: 0 !important;font-size: 0 !important;">&nbsp;</td>
                <td align="right" valign="bottom" class="btnRgBt" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;background-color: #424242;line-height: 100%;width: 4px;height: 4px;text-align: right;vertical-align: bottom;font-size: 0 !important;"><img src="<?php echo $this->config->item('email_asset');?>/mainBtn_rgbt.png" width="4" height="4" style="margin-top: 0;margin-left: auto;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;height: 4px;width: 4px;line-height: 0 !important;outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;font-size: 0 !important;"></td>
              </tr>
            </table></td>
          <!-- end .eBody--> 
        </tr>
        <tr>
          <td class="highlight invoiceHead" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 16px;padding-bottom: 0;padding-left: 16px;padding-right: 16px;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;width: 512px;text-align: left;font-size: 12px;color: #898989;background-color: #fafafa;border-bottom: 1px solid #ebebeb;"><table width="100%" border="0" cellspacing="0" cellpadding="0" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;mso-table-lspace: 0pt;mso-table-rspace: 0pt;border-collapse: collapse;border-spacing: 0;">
              <tr>
                <td align="left" valign="top" class="width184 pdRg16" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 16px;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;text-align: left;vertical-align: top;width: 184px;font-size: 12px;color: #898989;"><table border="0" cellpadding="0" cellspacing="0" class="tag" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;mso-table-lspace: 0pt;mso-table-rspace: 0pt;border-collapse: collapse;border-spacing: 0;">
                    <tr>
                      <td width="2" height="2" align="left" valign="top" class="btnLfTp" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;background-color: #cbcbcb;text-align: left;font-size: 0 !important;color: #898989;line-height: 100%;width: 2px;height: 2px;vertical-align: top;"><img src="<?php echo $this->config->item('email_asset');?>/tag_lftp.png" width="2" height="2" style="margin-top: 0;margin-left: 0;margin-right: auto;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;height: 2px;width: 2px;line-height: 0 !important;outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;font-size: 0 !important;"></td>
                      <td width="4" class="emptyCell" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;text-align: left;font-size: 0 !important;color: #898989;background-color: #cbcbcb;line-height: 0 !important;">&nbsp;</td>
                      <td width="4" height="8" align="right" valign="top" class="btnRgTp" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;background-color: #cbcbcb;text-align: right;font-size: 0 !important;color: #898989;line-height: 100%;width: 2px;height: 2px;vertical-align: top;"><img src="<?php echo $this->config->item('email_asset');?>/tag_rgtp.png" width="2" height="2" style="margin-top: 0;margin-left: auto;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;height: 2px;width: 2px;line-height: 0 !important;outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;font-size: 0 !important;"></td>
                    </tr>
                    <tr>
                      <td width="4" class="emptyCell" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;text-align: left;font-size: 0 !important;color: #898989;background-color: #cbcbcb;line-height: 0 !important;">&nbsp;</td>
                      <td align="left" valign="middle" class="tagName" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 2px;padding-bottom: 2px;padding-left: 4px;padding-right: 4px;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;text-align: left;font-size: 11px;color: #ffffff;background-color: #cbcbcb;text-transform: uppercase;white-space: nowrap;">Client</td>
                      <td width="4" class="emptyCell" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;text-align: left;font-size: 0 !important;color: #898989;background-color: #cbcbcb;line-height: 0 !important;">&nbsp;</td>
                    </tr>
                    <tr>
                      <td align="left" valign="bottom" class="btnLfBt" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;background-color: #cbcbcb;text-align: left;font-size: 0 !important;color: #898989;line-height: 100%;width: 2px;height: 2px;vertical-align: bottom;"><img src="<?php echo $this->config->item('email_asset');?>/tag_lfbt.png" width="2" height="2" style="margin-top: 0;margin-left: 0;margin-right: auto;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;height: 2px;width: 2px;line-height: 0 !important;outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;font-size: 0 !important;"></td>
                      <td width="4" class="emptyCell" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;text-align: left;font-size: 0 !important;color: #898989;background-color: #cbcbcb;line-height: 0 !important;">&nbsp;</td>
                      <td align="right" valign="bottom" class="btnRgBt" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;background-color: #cbcbcb;text-align: right;font-size: 0 !important;color: #898989;line-height: 100%;width: 2px;height: 2px;vertical-align: bottom;"><img src="<?php echo $this->config->item('email_asset');?>/tag_rgbt.png" width="2" height="2" style="margin-top: 0;margin-left: auto;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;height: 2px;width: 2px;line-height: 0 !important;outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;font-size: 0 !important;"></td>
                    </tr>
                    <tr>
                      <td class="tag_space emptyCell" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;text-align: left;font-size: 0 !important;color: #898989;background-color: transparent;line-height: 0 !important;height: 4px;">&nbsp;</td>
                      <td class="tag_space emptyCell" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;text-align: left;font-size: 0 !important;color: #898989;background-color: transparent;line-height: 0 !important;height: 4px;">&nbsp;</td>
                      <td class="tag_space emptyCell" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;text-align: left;font-size: 0 !important;color: #898989;background-color: transparent;line-height: 0 !important;height: 4px;">&nbsp;</td>
                    </tr>
                  </table>
                  <p style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 24px;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;font-size: 12px;line-height: 19px;text-align: left;color: #898989;"><span class="ihBlack" style="color: #242424;">Connie S. Smythe</span><br>
                    Eisner Food Store<br>
                    753 Lakeland Terrace<br>
                    Southfield, MI 48075<br>
                    USA</p></td>
                <td class="alignLeft" align="left" valign="top" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;text-align: left;font-size: 12px;color: #898989;"><table border="0" cellpadding="0" cellspacing="0" class="tag" style="margin-top: 0;margin-left: 0;margin-right: auto;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;mso-table-lspace: 0pt;mso-table-rspace: 0pt;border-collapse: collapse;border-spacing: 0;">
                    <tr>
                      <td width="2" height="2" align="left" valign="top" class="btnLfTp" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;background-color: #cbcbcb;text-align: left;font-size: 0 !important;color: #898989;line-height: 100%;width: 2px;height: 2px;vertical-align: top;"><img src="<?php echo $this->config->item('email_asset');?>/tag_lftp.png" width="2" height="2" style="margin-top: 0;margin-left: 0;margin-right: auto;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;height: 2px;width: 2px;line-height: 0 !important;outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;font-size: 0 !important;"></td>
                      <td width="4" class="emptyCell" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;text-align: left;font-size: 0 !important;color: #898989;background-color: #cbcbcb;line-height: 0 !important;">&nbsp;</td>
                      <td width="4" height="8" align="right" valign="top" class="btnRgTp" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;background-color: #cbcbcb;text-align: right;font-size: 0 !important;color: #898989;line-height: 100%;width: 2px;height: 2px;vertical-align: top;"><img src="<?php echo $this->config->item('email_asset');?>/tag_rgtp.png" width="2" height="2" style="margin-top: 0;margin-left: auto;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;height: 2px;width: 2px;line-height: 0 !important;outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;font-size: 0 !important;"></td>
                    </tr>
                    <tr>
                      <td width="4" class="emptyCell" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;text-align: left;font-size: 0 !important;color: #898989;background-color: #cbcbcb;line-height: 0 !important;">&nbsp;</td>
                      <td align="left" valign="middle" class="tagName" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 2px;padding-bottom: 2px;padding-left: 4px;padding-right: 4px;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;text-align: left;font-size: 11px;color: #ffffff;background-color: #cbcbcb;text-transform: uppercase;white-space: nowrap;">Payment&nbsp;Details&nbsp;</td>
                      <td width="4" class="emptyCell" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;text-align: left;font-size: 0 !important;color: #898989;background-color: #cbcbcb;line-height: 0 !important;">&nbsp;</td>
                    </tr>
                    <tr>
                      <td align="left" valign="bottom" class="btnLfBt" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;background-color: #cbcbcb;text-align: left;font-size: 0 !important;color: #898989;line-height: 100%;width: 2px;height: 2px;vertical-align: bottom;"><img src="<?php echo $this->config->item('email_asset');?>/tag_lfbt.png" width="2" height="2" style="margin-top: 0;margin-left: 0;margin-right: auto;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;height: 2px;width: 2px;line-height: 0 !important;outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;font-size: 0 !important;"></td>
                      <td width="4" class="emptyCell" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;text-align: left;font-size: 0 !important;color: #898989;background-color: #cbcbcb;line-height: 0 !important;">&nbsp;</td>
                      <td align="right" valign="bottom" class="btnRgBt" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;background-color: #cbcbcb;text-align: right;font-size: 0 !important;color: #898989;line-height: 100%;width: 2px;height: 2px;vertical-align: bottom;"><img src="<?php echo $this->config->item('email_asset');?>/tag_rgbt.png" width="2" height="2" style="margin-top: 0;margin-left: auto;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;height: 2px;width: 2px;line-height: 0 !important;outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;font-size: 0 !important;"></td>
                    </tr>
                    <tr>
                      <td class="tag_space emptyCell" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;text-align: left;font-size: 0 !important;color: #898989;background-color: transparent;line-height: 0 !important;height: 4px;">&nbsp;</td>
                      <td class="tag_space emptyCell" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;text-align: left;font-size: 0 !important;color: #898989;background-color: transparent;line-height: 0 !important;height: 4px;">&nbsp;</td>
                      <td class="tag_space emptyCell" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;text-align: left;font-size: 0 !important;color: #898989;background-color: transparent;line-height: 0 !important;height: 4px;">&nbsp;</td>
                    </tr>
                  </table>
                  <p class="ihBlack" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 24px;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;font-size: 12px;line-height: 19px;text-align: left;color: #242424;">VISA -XXX-321</p></td>
                <td align="left" valign="top" class="width116 pdRg16" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 16px;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;text-align: left;vertical-align: top;width: 116px;font-size: 12px;color: #898989;"><table border="0" cellpadding="0" cellspacing="0" class="tag" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;mso-table-lspace: 0pt;mso-table-rspace: 0pt;border-collapse: collapse;border-spacing: 0;">
                    <tr>
                      <td width="2" height="2" align="left" valign="top" class="btnLfTp" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;background-color: #cbcbcb;text-align: left;font-size: 0 !important;color: #898989;line-height: 100%;width: 2px;height: 2px;vertical-align: top;"><img src="<?php echo $this->config->item('email_asset');?>/tag_lftp.png" width="2" height="2" style="margin-top: 0;margin-left: 0;margin-right: auto;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;height: 2px;width: 2px;line-height: 0 !important;outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;font-size: 0 !important;"></td>
                      <td width="4" class="emptyCell" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;text-align: left;font-size: 0 !important;color: #898989;background-color: #cbcbcb;line-height: 0 !important;">&nbsp;</td>
                      <td width="4" height="8" align="right" valign="top" class="btnRgTp" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;background-color: #cbcbcb;text-align: right;font-size: 0 !important;color: #898989;line-height: 100%;width: 2px;height: 2px;vertical-align: top;"><img src="<?php echo $this->config->item('email_asset');?>/tag_rgtp.png" width="2" height="2" style="margin-top: 0;margin-left: auto;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;height: 2px;width: 2px;line-height: 0 !important;outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;font-size: 0 !important;"></td>
                    </tr>
                    <tr>
                      <td width="4" class="emptyCell" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;text-align: left;font-size: 0 !important;color: #898989;background-color: #cbcbcb;line-height: 0 !important;">&nbsp;</td>
                      <td align="left" valign="middle" class="tagName" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 2px;padding-bottom: 2px;padding-left: 4px;padding-right: 4px;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;text-align: left;font-size: 11px;color: #ffffff;background-color: #cbcbcb;text-transform: uppercase;white-space: nowrap;">Total</td>
                      <td width="4" class="emptyCell" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;text-align: left;font-size: 0 !important;color: #898989;background-color: #cbcbcb;line-height: 0 !important;">&nbsp;</td>
                    </tr>
                    <tr>
                      <td align="left" valign="bottom" class="btnLfBt" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;background-color: #cbcbcb;text-align: left;font-size: 0 !important;color: #898989;line-height: 100%;width: 2px;height: 2px;vertical-align: bottom;"><img src="<?php echo $this->config->item('email_asset');?>/tag_lfbt.png" width="2" height="2" style="margin-top: 0;margin-left: 0;margin-right: auto;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;height: 2px;width: 2px;line-height: 0 !important;outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;font-size: 0 !important;"></td>
                      <td width="4" class="emptyCell" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;text-align: left;font-size: 0 !important;color: #898989;background-color: #cbcbcb;line-height: 0 !important;">&nbsp;</td>
                      <td align="right" valign="bottom" class="btnRgBt" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;background-color: #cbcbcb;text-align: right;font-size: 0 !important;color: #898989;line-height: 100%;width: 2px;height: 2px;vertical-align: bottom;"><img src="<?php echo $this->config->item('email_asset');?>/tag_rgbt.png" width="2" height="2" style="margin-top: 0;margin-left: auto;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;height: 2px;width: 2px;line-height: 0 !important;outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;font-size: 0 !important;"></td>
                    </tr>
                    <tr>
                      <td class="tag_space emptyCell" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;text-align: left;font-size: 0 !important;color: #898989;background-color: transparent;line-height: 0 !important;height: 4px;">&nbsp;</td>
                      <td class="tag_space emptyCell" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;text-align: left;font-size: 0 !important;color: #898989;background-color: transparent;line-height: 0 !important;height: 4px;">&nbsp;</td>
                      <td class="tag_space emptyCell" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;text-align: left;font-size: 0 !important;color: #898989;background-color: transparent;line-height: 0 !important;height: 4px;">&nbsp;</td>
                    </tr>
                  </table>
                  <p class="amount" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 24px;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;color: #242424;font-size: 16px;line-height: 19px;text-align: left;font-weight: bold;">$2.728</p></td>
              </tr>
            </table></td>
          <!-- end .highlight--> 
        </tr>
        <tr>
          <td style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;"><table width="100%" border="0" cellpadding="0" cellspacing="0" class="invoiceTable2 invoiceTable3" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;mso-table-lspace: 0pt;mso-table-rspace: 0pt;border-collapse: collapse;border-spacing: 0;background-color: #ffffff;">
              <tr>
                <th colspan="2" class="alignLeft pdLf16" style="-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;text-align: left;padding-left: 16px;padding-top: 6px;padding-bottom: 6px;padding-right: 16px;font-size: 12px;line-height: 16px;font-weight: bold;text-transform: uppercase;border-bottom: 1px solid #ebebeb;color: #898989;background-color: #ffffff;">Item</th>
                <th class="width64 alignCenter" style="-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;text-align: left;vertical-align: top;width: 64px;padding-top: 6px;padding-bottom: 6px;padding-left: 0;padding-right: 16px;font-size: 12px;line-height: 16px;font-weight: bold;text-transform: uppercase;border-bottom: 1px solid #ebebeb;color: #898989;background-color: #ffffff;">Price</th>
                <th class="alignCenter eQuantity" style="-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;text-align: center;padding-top: 6px;padding-bottom: 6px;padding-left: 0;padding-right: 0;font-size: 12px;line-height: 16px;font-weight: bold;text-transform: uppercase;border-bottom: 1px solid #ebebeb;color: #898989;background-color: #ffffff;width: 40px;vertical-align: top;">Qty</th>
                <th class="width64 alignRight" style="-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;text-align: right;vertical-align: top;width: 64px;padding-top: 6px;padding-bottom: 6px;padding-left: 0;padding-right: 16px;font-size: 12px;line-height: 16px;font-weight: bold;text-transform: uppercase;border-bottom: 1px solid #ebebeb;color: #898989;background-color: #ffffff;">Subtotal</th>
              </tr>
              <tr>
                <td colspan="5" class="alignLeft prodTitle" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 12px;padding-bottom: 0;padding-left: 16px;padding-right: 16px;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;text-align: left;font-size: 14px;line-height: 19px;color: #242424;background-color: #ffffff;border-bottom: 0;border-top: 1px solid #ebebeb;"><h4 style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 5px;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;font-size: 14px;font-weight: bold;color: #242424;"><a href="#" style="padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;display: inline-block;text-decoration: none;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;color: #0dc0c0;">MacBook Pro 13-inch: 2.5GHz</a></h4></td>
              </tr>
              <tr>
                <td class="alignLeft width80 prodImg" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 14px;padding-left: 16px;padding-right: 10px;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;text-align: left;vertical-align: top;width: 80px;font-size: 14px;line-height: 19px;color: #242424;background-color: #ffffff;"><img src="<?php echo $this->config->item('email_asset');?>/product_thumb.jpg" width="80" height="80" alt="MacBook Pro 13-inch: 2.5GHz" style="margin-top: 0;margin-left: 0;margin-right: auto;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;height: auto;width: auto;line-height: 100%;outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;"></td>
                <td class="alignLeft prodDesc" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 14px;padding-left: 0;padding-right: 8px;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;text-align: left;font-size: 12px;line-height: 18px;color: #898989;background-color: #ffffff;vertical-align: top;">Suspendisse odio mi, feugiat et dictum sed, eleifend eget libero. </td>
                <td class="width64 alignCenter" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 14px;padding-left: 0;padding-right: 16px;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;text-align: left;vertical-align: top;width: 64px;font-size: 14px;line-height: 19px;color: #242424;background-color: #ffffff;"><span class="desktopHide" style="display: none;font-size: 0;max-height: 0;width: 0;line-height: 0;overflow: hidden;mso-hide: all;">Price: </span>$600</td>
                <td class="alignCenter eQuantity" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 14px;padding-left: 0;padding-right: 0;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;text-align: center;font-size: 14px;line-height: 19px;color: #242424;background-color: #ffffff;width: 40px;vertical-align: top;"><span class="desktopHide" style="display: none;font-size: 0;max-height: 0;width: 0;line-height: 0;overflow: hidden;mso-hide: all;">Quantity: </span>2</td>
                <td class="width64 alignRight" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 14px;padding-left: 0;padding-right: 16px;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;text-align: right;vertical-align: top;width: 64px;font-size: 14px;line-height: 19px;color: #242424;background-color: #ffffff;"><span class="desktopHide" style="display: none;font-size: 0;max-height: 0;width: 0;line-height: 0;overflow: hidden;mso-hide: all;">Subtotal: </span><span class="amount" style="color: #666666;">$1,200</span></td>
              </tr>
              <tr>
                <td colspan="5" class="alignLeft prodTitle" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 12px;padding-bottom: 0;padding-left: 16px;padding-right: 16px;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;text-align: left;font-size: 14px;line-height: 19px;color: #242424;background-color: #ffffff;border-bottom: 0;border-top: 1px solid #ebebeb;"><h4 style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 5px;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;font-size: 14px;font-weight: bold;color: #242424;"><a href="#" style="padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;display: inline-block;text-decoration: none;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;color: #0dc0c0;">SimpleApp Charity Cubcakes</a></h4></td>
              </tr>
              <tr>
                <td class="alignLeft width80 prodImg" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 14px;padding-left: 16px;padding-right: 10px;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;text-align: left;vertical-align: top;width: 80px;font-size: 14px;line-height: 19px;color: #242424;background-color: #ffffff;"><img src="<?php echo $this->config->item('email_asset');?>/product_thumb2.jpg" width="80" height="80" alt="SimpleApp Charity Cubcakes" style="margin-top: 0;margin-left: 0;margin-right: auto;margin-bottom: 0;padding-top: 0;padding-bottom: 0;padding-left: 0;padding-right: 0;height: auto;width: auto;line-height: 100%;outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;"></td>
                <td class="alignLeft prodDesc" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 14px;padding-left: 0;padding-right: 8px;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;text-align: left;font-size: 12px;line-height: 18px;color: #898989;background-color: #ffffff;vertical-align: top;">Etiam facilisis nulla nec purus consectetur ut porta metus imperdiet.</td>
                <td class="width64 alignCenter" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 14px;padding-left: 0;padding-right: 16px;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;text-align: left;vertical-align: top;width: 64px;font-size: 14px;line-height: 19px;color: #242424;background-color: #ffffff;"><span class="desktopHide" style="display: none;font-size: 0;max-height: 0;width: 0;line-height: 0;overflow: hidden;mso-hide: all;">Price: </span>$100</td>
                <td align="left" valign="top" class="alignCenter eQuantity" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 14px;padding-left: 0;padding-right: 0;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;text-align: center;font-size: 14px;line-height: 19px;color: #242424;background-color: #ffffff;width: 40px;vertical-align: top;"><span class="desktopHide" style="display: none;font-size: 0;max-height: 0;width: 0;line-height: 0;overflow: hidden;mso-hide: all;">Quantity: </span>10</td>
                <td class="width64 alignRight" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 14px;padding-left: 0;padding-right: 16px;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;text-align: right;vertical-align: top;width: 64px;font-size: 14px;line-height: 19px;color: #242424;background-color: #ffffff;"><span class="desktopHide" style="display: none;font-size: 0;max-height: 0;width: 0;line-height: 0;overflow: hidden;mso-hide: all;">Subtotal: </span><span class="amount" style="color: #666666;">$1,000</span></td>
              </tr>
              <tr>
                <td colspan="4" class="width448 subTotal alignRight mobileHide" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 16px;padding-bottom: 14px;padding-left: 0;padding-right: 16px;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;text-align: right;vertical-align: top;width: 448px;border-bottom: 1px solid #ebebeb;font-size: 14px;line-height: 22px;color: #898989;background-color: #fafafa;">Subtotal</td>
                <td class="width64 subTotal alignRight" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 16px;padding-bottom: 14px;padding-left: 0;padding-right: 16px;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;text-align: right;vertical-align: top;width: 64px;border-bottom: 1px solid #ebebeb;font-size: 14px;line-height: 22px;color: #898989;background-color: #fafafa;"><span class="desktopHide" style="display: none;font-size: 0;max-height: 0;width: 0;line-height: 0;overflow: hidden;mso-hide: all;">Subtotal: </span><span class="amount" style="color: #242424;">$2,200</span></td>
              </tr>
              <tr>
                <td colspan="4" class="width448 eTotal alignRight" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 16px;padding-bottom: 14px;padding-left: 0;padding-right: 16px;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;text-align: right;vertical-align: top;width: 448px;border-bottom: 1px solid #ebebeb;font-size: 14px;line-height: 19px;color: #242424;background-color: #ffffff;"><strong>Total</strong> due by Sep 10, 2014</td>
                <td class="width64 eTotal alignRight" style="margin-top: 0;margin-left: 0;margin-right: 0;margin-bottom: 0;padding-top: 16px;padding-bottom: 14px;padding-left: 0;padding-right: 16px;border-collapse: collapse;border-spacing: 0;-webkit-text-size-adjust: none;font-family: Arial, Helvetica, sans-serif;text-align: right;vertical-align: top;width: 64px;border-bottom: 1px solid #ebebeb;font-size: 14px;line-height: 19px;color: #242424;background-color: #ffffff;"><span class="amount" style="color: #666666;font-size: 16px;font-weight: bold;">$2,200</span></td>
              </tr>
            </table></td>
          <!-- end order body --> 
        </tr>